version: '3'

services:
  blogApp-db:
    image: mongo:5.0.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: password311
    ports:
      - "27017"
    volumes:
      - mongo-db:/data/db
    networks:
      - private-network
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: andre/backend
    container_name: backend
    networks:
      - private-network
      - app-network
    depends_on:
      - blogApp-db
    ports:
      - 8080:8080
      
volumes:
  mongo-db:
    name: 'mongo-db'

networks:
  app-network:
    name: app-network
  private-network:
    name: private-network